"""HTTP views for the 中燃在线 (ZR Gas) integration.

Provides a custom HTTP endpoint to serve captcha images during the
Config Flow. This is necessary because:

1. The remote captcha URL cannot be loaded directly in the HA frontend
   (CORS / session cookie issues)
2. Base64 data URIs in Markdown descriptions are stripped by HA's
   DOMPurify sanitizer
3. Serving from HA's own HTTP server ensures same-origin access

The captcha image bytes are stored in ``hass.data[DOMAIN]["captcha_images"]``
by the Config Flow, keyed by a random UUID token (not the mobile number,
for privacy). The view reads from this store and serves the image.
"""

from __future__ import annotations

from aiohttp import web
from homeassistant.components.http import HomeAssistantView

from .const import DOMAIN


class ZrGasCaptchaView(HomeAssistantView):
    """Serve captcha images for the Config Flow.

    URL pattern: ``/api/zr_gas/captcha/{token}``
    The token is a random UUID generated by the Config Flow.
    """

    url = "/api/zr_gas/captcha/{token}"
    name = "api:zr_gas:captcha"
    requires_auth = False

    async def get(self, request: web.Request, token: str) -> web.Response:
        """Return the captcha image for the given token.

        Args:
            request: The HTTP request.
            token: UUID token that maps to a stored captcha image.

        Returns:
            PNG image response, or 404 if token not found/expired.
        """
        hass = request.app["hass"]
        captcha_images = hass.data.get(DOMAIN, {}).get("captcha_images", {})
        image_bytes = captcha_images.get(token)

        if image_bytes is None:
            return web.Response(
                status=404,
                text="Captcha image not found or expired",
            )

        return web.Response(
            body=image_bytes,
            content_type="image/png",
            headers={
                "Cache-Control": "no-cache, no-store, must-revalidate",
                "Pragma": "no-cache",
            },
        )
